-- 🎬 movemovemovie : Supabase Schema Setup (Clean Version) --
-- 🚀 Copy and paste this entire script into your Supabase SQL Editor and hit RUN!

-- 0. Clean old tables if they exist
DROP TABLE IF EXISTS ads CASCADE;
DROP TABLE IF EXISTS rewards CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS scenes CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS points CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 1. Create tables
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'member',
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userId BIGINT REFERENCES users(id) ON DELETE CASCADE,
  amount INT DEFAULT 0
);

CREATE TABLE movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  poster TEXT,
  genre TEXT,
  releaseYear INT,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  province TEXT,
  type TEXT,
  lat FLOAT,
  lng FLOAT,
  imgUrl TEXT,
  hidden BOOLEAN DEFAULT false,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE scenes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movieId BIGINT REFERENCES movies(id) ON DELETE CASCADE,
  locationId BIGINT REFERENCES locations(id) ON DELETE CASCADE,
  description TEXT,
  imgUrl TEXT
);

CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userId BIGINT REFERENCES users(id) ON DELETE CASCADE,
  userName TEXT,
  locationId BIGINT REFERENCES locations(id) ON DELETE CASCADE,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE rewards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  points INT NOT NULL,
  stock INT DEFAULT 0,
  img TEXT,
  hidden BOOLEAN DEFAULT false
);

CREATE TABLE ads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partnerId BIGINT REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  movieId BIGINT REFERENCES movies(id) ON DELETE CASCADE,
  lat FLOAT,
  lng FLOAT,
  pointsrequired INT DEFAULT 0,
  hidden BOOLEAN DEFAULT true,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid BIGINT REFERENCES users(id) ON DELETE CASCADE,
  adid BIGINT REFERENCES ads(id) ON DELETE CASCADE,
  ticket_code TEXT UNIQUE,
  used BOOLEAN DEFAULT false,
  redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insert Default Data (Seed) --
INSERT INTO users (id, email, password, name, role) VALUES 
(1, 'admin@mmm.com', 'admin', 'Admin', 'admin'),
(2, 'user@mmm.com', 'user', 'Member A', 'member'),
(3, 'partner@mmm.com', 'partner', 'Partner One', 'partner');

INSERT INTO points (userId, amount) VALUES 
(1, 0),
(2, 600),
(3, 100);

-- Make sure sequence resumes from 4
ALTER SEQUENCE users_id_seq RESTART WITH 4;
ALTER SEQUENCE points_id_seq RESTART WITH 4;

INSERT INTO movies (id, title, poster, description, releaseYear, genre) VALUES 
(1, 'พี่มาก..พระโขนง', 'https://picsum.photos/500/750?movie=1', 'ภาพยนตร์สยองขวัญสุดฮิต ตำนานรักพี่มากและแม่นาคที่ทำรายได้ทะลุพันล้าน', 2013, 'Horror'),
(2, 'ฉลาดเกมส์โกง', 'https://picsum.photos/500/750?movie=2', 'เรื่องราวของนักเรียนหญิงฉลาดที่พลิกแพลงการโกงข้อสอบระดับโลก', 2017, 'Thriller');

ALTER SEQUENCE movies_id_seq RESTART WITH 3;

INSERT INTO locations (id, name, lat, lng, province, description, type, hidden) VALUES
(1, 'วัดมหาบุศย์ พระโขนง', 13.7063, 100.6018, 'Bangkok', 'วัดเก่าแก่ริมคลอง... ถ่ายทำพี่มาก', 'Temple', false);

ALTER SEQUENCE locations_id_seq RESTART WITH 2;

INSERT INTO scenes (id, movieId, locationId, description, imgUrl) VALUES
(1, 1, 1, 'ฉากที่มากและเพื่อนมาเยี่ยมนาค', 'https://picsum.photos/400/250?scene=1');

ALTER SEQUENCE scenes_id_seq RESTART WITH 2;

INSERT INTO reviews (id, userId, userName, locationId, rating, comment) VALUES
(1, 2, 'Member A', 1, 5, 'สวยงาม บรรยากาศสมจริง น่ากลัวนิดๆ');

ALTER SEQUENCE reviews_id_seq RESTART WITH 2;

INSERT INTO rewards (id, title, points, stock, img, hidden) VALUES
(1, 'ตั๋วหนังฟรี 1 ที่นั่ง', 500, 10, 'https://picsum.photos/300/200?ticket', false);

ALTER SEQUENCE rewards_id_seq RESTART WITH 2;

INSERT INTO ads (id, partnerId, title, description, lat, lng, pointsrequired, hidden) VALUES
(1, 3, 'โปรพักโรงแรมใกล้ที่ถ่ายทำ', 'ส่วนลด 20% สำหรับแฟนคลับ', 13.7063, 100.6018, 500, false);

ALTER SEQUENCE ads_id_seq RESTART WITH 2;

-- Allow Anon Role to interact with all tables (Temporary setup for fast prototyping without deep Auth RLS barriers)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon;
